from .base_agent import Agent
from ..trade_executor import TradeExecutor
try:
    import MetaTrader5 as mt5
except ImportError:
    from .. import mock_metatrader5 as mt5

class TraderAgent(Agent):
    def __init__(self, name, llm_client, mt5_connection):
        super().__init__(name, llm_client)
        self.trade_executor = TradeExecutor(mt5_connection)

    def execute(self, research_consensus):
        """
        Makes a trading decision based on the research consensus using the LLM,
        and then executes the trade.
        """
        prompt = (
            "You are a professional Forex trader. Based on the following research consensus, "
            "formulate a precise and actionable trade plan. Specify the currency pair, "
            "trade direction (buy/sell), entry price, stop-loss, take-profit, and lot size "
            "for a $10,000 account with a 2% risk tolerance.\n\n"
            f"Research Consensus:\n{research_consensus}"
        )

        trade_decision_str = self.llm_client.generate_response(prompt)

        # Ensure a string is always returned, even if LLM generates nothing or an unexpected output
        if not isinstance(trade_decision_str, str) or not trade_decision_str.strip():
            trade_decision_str = "No specific trade decision could be generated by the LLM in this cycle."
            print("Warning: TraderAgent LLM did not return a valid trade decision string.")

        print(f"LLM Trade Decision:\n{trade_decision_str}")
        return trade_decision_str
